-- MySQL Script generated by MySQL Workbench
-- Fri Aug 26 21:13:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERSONA` (
  `id_persona` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `acerca_de` VARCHAR(2000) NULL,
  `linkedin` VARCHAR(45) NOT NULL,
  `github` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EXPERIENCIA_LABORAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EXPERIENCIA_LABORAL` (
  `id_experiencia` INT NOT NULL,
  `puesto` VARCHAR(200) NOT NULL,
  `periodo` VARCHAR(45) NOT NULL,
  `logo` VARCHAR(100) NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `PERSONA_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_experiencia`),
  INDEX `fk_EXPERIENCIA_LABORAL_PERSONA1_idx` (`PERSONA_id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_EXPERIENCIA_LABORAL_PERSONA1`
    FOREIGN KEY (`PERSONA_id_persona`)
    REFERENCES `mydb`.`PERSONA` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EDUCACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EDUCACION` (
  `id_educacion` INT NOT NULL,
  `logo` VARCHAR(100) NULL,
  `duracion` VARCHAR(45) NOT NULL,
  `instituto` VARCHAR(45) NOT NULL,
  `PERSONA_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_educacion`),
  INDEX `fk_EDUCACION_PERSONA1_idx` (`PERSONA_id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_EDUCACION_PERSONA1`
    FOREIGN KEY (`PERSONA_id_persona`)
    REFERENCES `mydb`.`PERSONA` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIOS` (
  `id_usuarios` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `PERSONA_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_usuarios`),
  INDEX `fk_USUARIOS_PERSONA1_idx` (`PERSONA_id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIOS_PERSONA1`
    FOREIGN KEY (`PERSONA_id_persona`)
    REFERENCES `mydb`.`PERSONA` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROYECTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROYECTOS` (
  `id_proyectos` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(2000) NOT NULL,
  `codigo_fuente` VARCHAR(500) NOT NULL,
  `vista_proyecto` VARCHAR(500) NULL,
  `PERSONA_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_proyectos`),
  INDEX `fk_PROYECTOS_PERSONA_idx` (`PERSONA_id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_PROYECTOS_PERSONA`
    FOREIGN KEY (`PERSONA_id_persona`)
    REFERENCES `mydb`.`PERSONA` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TECNOLOGIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TECNOLOGIAS` (
  `id_tecnologia` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `nivel` INT NOT NULL DEFAULT 0,
  `PERSONA_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_tecnologia`),
  INDEX `fk_TECNOLOGIAS_PERSONA1_idx` (`PERSONA_id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_TECNOLOGIAS_PERSONA1`
    FOREIGN KEY (`PERSONA_id_persona`)
    REFERENCES `mydb`.`PERSONA` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
